---
capture_device: 0

car_length: 105

ball:
  - lower: [20, 64, 192]
    upper: [40, 255, 255]

blue_car:
  - lower: [110, 64, 64]
    upper: [130, 255, 255]

red_car:
  - lower: [170, 64, 128]
    upper: [180, 255, 255]
  - lower: [0, 64, 128]
    upper: [10, 255, 255]
